# Generated by Django 2.1.7 on 2019-06-02 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataconfigurator', '0001_initial'),
        ('testenvconfig', '0004_auto_20190422_2327'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='用例名')),
                ('req_method', models.CharField(choices=[('GET', 'get'), ('POST', 'post'), ('PUT', 'put'), ('DELETE', 'delete')], default=('GET', 'get'), max_length=6)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('createby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casecreater', to=settings.AUTH_USER_MODEL)),
                ('updateby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caseupdater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case_Source_RouteParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myCSRP', to='tester.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Case_Source_RouteResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myCSRR', to='tester.Case')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseGroupParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=16, verbose_name='参数名')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='routeName')),
                ('route', models.CharField(max_length=50, verbose_name='route')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myroute', to='testenvconfig.Project')),
            ],
        ),
        migrations.CreateModel(
            name='RouteParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=16, verbose_name='参数名')),
                ('datatype', models.CharField(choices=[(0, 'header'), (1, 'param'), (2, 'body'), (3, 'url_param')], default=1, max_length=1, verbose_name='参数形式')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myrouteparams', to='tester.Route', verbose_name='所属路由')),
            ],
        ),
        migrations.CreateModel(
            name='RouteResponseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='responseGroupName')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myresponsegroup', to='tester.Route', verbose_name='所属路由')),
            ],
        ),
        migrations.AddField(
            model_name='responsegroupparam',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mygroupparams', to='tester.RouteResponseGroup'),
        ),
        migrations.AddField(
            model_name='case_source_routeresponse',
            name='param',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tester.RouteParams'),
        ),
        migrations.AddField(
            model_name='case_source_routeresponse',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataconfigurator.SourceResult'),
        ),
        migrations.AddField(
            model_name='case_source_routeparam',
            name='param',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tester.RouteParams'),
        ),
        migrations.AddField(
            model_name='case_source_routeparam',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataconfigurator.SourceResult'),
        ),
        migrations.AlterUniqueTogether(
            name='case_source_routeresponse',
            unique_together={('case', 'param', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='case_source_routeparam',
            unique_together={('case', 'param', 'value')},
        ),
    ]
