# Generated by Django 2.2.1 on 2019-06-11 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_source_routeresponse',
            name='param',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tester.ResponseGroupParam'),
        ),
    ]
