# Generated by Django 2.2.1 on 2019-06-12 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataconfigurator', '0001_initial'),
        ('tester', '0002_auto_20190611_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case_source_routeparam',
            old_name='value',
            new_name='data_source',
        ),
        migrations.RenameField(
            model_name='case_source_routeparam',
            old_name='param',
            new_name='route_param',
        ),
        migrations.RenameField(
            model_name='case_source_routeresponse',
            old_name='value',
            new_name='data_source',
        ),
        migrations.RenameField(
            model_name='case_source_routeresponse',
            old_name='param',
            new_name='response',
        ),
        migrations.AlterUniqueTogether(
            name='case_source_routeparam',
            unique_together={('case', 'route_param', 'data_source')},
        ),
        migrations.AlterUniqueTogether(
            name='case_source_routeresponse',
            unique_together={('case', 'response', 'data_source')},
        ),
    ]
