# Generated by Django 2.2.1 on 2019-06-18 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testenvconfig', '0004_auto_20190422_2327'),
        ('tester', '0003_auto_20190612_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mycase', to='testenvconfig.Project'),
            preserve_default=False,
        ),
    ]
