# Generated by Django 2.2.1 on 2019-06-25 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testenvconfig', '0004_auto_20190422_2327'),
        ('tester', '0005_auto_20190625_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='任务简介'),
        ),
        migrations.AddField(
            model_name='task',
            name='env_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myTask', to='testenvconfig.ProjectConfig'),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=16, verbose_name='任务名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='myTask', to='testenvconfig.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='首次启动时间'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Task2Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('disabled', models.BooleanField(default=True, verbose_name='启用状态')),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myTask', to='tester.Case')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TaskCreatedSelf', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myCase', to='tester.Task')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TaskIUpdatedSelf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
