# Generated by Django 2.2.1 on 2019-06-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0006_auto_20190625_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
        migrations.AddField(
            model_name='task',
            name='jenkins_job',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='jenkins任务ID'),
        ),
    ]
