# Generated by Django 2.2.1 on 2019-06-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0007_auto_20190627_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task2case',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task2case',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
