# Generated by Django 2.2.1 on 2019-07-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0008_auto_20190627_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task2case',
            name='disabled',
        ),
        migrations.AddField(
            model_name='case',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='fixed',
            field=models.CharField(choices=[(0, 'normal'), (1, 'error')], default=0, max_length=1),
        ),
    ]
