# Generated by Django 2.2.1 on 2019-07-09 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0009_auto_20190709_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='jenkins_job',
        ),
    ]
