# Generated by Django 2.2.1 on 2019-07-31 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0011_auto_20190709_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mycase', to='tester.Route'),
            preserve_default=False,
        ),
    ]
