# Generated by Django 2.2.1 on 2019-08-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0013_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='buildNumber',
            field=models.CharField(default=1, max_length=4, verbose_name='buildNumber'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('buildNumber', 'task')},
        ),
        migrations.RemoveField(
            model_name='result',
            name='run_id',
        ),
    ]
