# Generated by Django 2.2.1 on 2019-08-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0014_auto_20190805_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='任务名称'),
        ),
    ]
