# Generated by Django 2.2.1 on 2019-08-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0016_auto_20190809_1919'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set(),
        ),
    ]
