# Generated by Django 2.1.7 on 2019-04-21 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testenvconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='u2p',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
