# Generated by Django 2.1.7 on 2019-04-22 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testenvconfig', '0002_auto_20190422_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u2p',
            name='Pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='testenvconfig.Project'),
        ),
        migrations.AlterField(
            model_name='u2p',
            name='Uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
