# Generated by Django 2.1.7 on 2019-04-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testenvconfig', '0003_auto_20190422_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='u2p',
            old_name='Pid',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='u2p',
            old_name='Uid',
            new_name='User',
        ),
    ]
