# Generated by Django 2.2.1 on 2019-08-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testenvconfig', '0004_auto_20190422_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectconfig',
            old_name='projectid',
            new_name='project',
        ),
    ]
