# Generated by Django 2.1.7 on 2019-06-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='源名')),
                ('source_type', models.CharField(choices=[(0, 'sql'), (1, 'fix'), (2, 'function')], default=1, max_length=1, verbose_name='数据源形式')),
                ('source_value_runner', models.TextField(max_length=500, verbose_name='源数据获取器')),
            ],
        ),
        migrations.CreateModel(
            name='SourceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='结果名')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dataconfigurator.DataSource')),
            ],
        ),
    ]
