# Generated by Django 2.2.1 on 2019-06-12 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testenvconfig', '0004_auto_20190422_2327'),
        ('dataconfigurator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mydatasource', to='testenvconfig.Project'),
            preserve_default=False,
        ),
    ]
