# Generated by Django 2.2.1 on 2019-06-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconfigurator', '0002_datasource_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='source_value_runner',
            new_name='source_runner',
        ),
        migrations.AddField(
            model_name='datasource',
            name='source_creater',
            field=models.TextField(default=1, max_length=500, verbose_name='源数据生成器'),
            preserve_default=False,
        ),
    ]
