# Generated by Django 2.2.1 on 2019-08-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconfigurator', '0003_auto_20190613_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=64, verbose_name='源名'),
        ),
    ]
