# Generated by Django 2.2.1 on 2019-08-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconfigurator', '0004_auto_20190809_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceresult',
            name='name',
            field=models.CharField(max_length=64, verbose_name='结果名'),
        ),
    ]
