# Generated by Django 2.2.1 on 2019-08-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconfigurator', '0005_auto_20190809_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_creater',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='源数据生成器'),
        ),
    ]
